name: Run automation tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone edx-app-test repository
      run: |
        git clone https://github.com/openedx/edx-app-test.git
        virtualenv workspace
        cd workspace
        source bin/activate
        pip install pytest
        pip install Appium-Python-Client
        find tests/
        py.test --collect-only tests/
        pip freeze > requirements.txt
        pip wheel --wheel-dir wheelhouse -r requirements.txt
        zip -r test_bundle.zip tests/ requirements.txt
