name: Run automation tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone edx-app-test repository
      run: |
        git clone https://github.com/openedx/edx-app-test.git
        cd edx-app-test
        zip -r test_bundle.zip tests/ requirements.txt
        cp test_bundle.zip ../
