name: "edX Test Suit"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  xcode-14:
    name: "${{ matrix.env.name }}"
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: "Test iOS 16"
            runtime: "iOS-16-4"
            device: "iPhone 14 Pro"
            task: "testLTRCurrentOS"
          - name: "Test RTL iOS 16"
            runtime: "iOS-16-4"
            device: "iPhone 14 Pro"
            task: "testRTLCurrentOS"
    steps:
      - name: "Select Xcode 14.3.1"
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.1.app
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run tests
        if: always()
        run: |
          TASK="${{ matrix.env.task }}"
          RUNTIME="${{ matrix.env.runtime }}"
          DEVICE="${{ matrix.env.device }}"
          DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \\-]+/ /g" -e "s/[^[:alnum:]]/-/g")
          RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \\-]+/ /g" -e "s/[^[:alnum:]]/-/g")
          DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
          xcrun simctl boot $DESTINATION_ID
          ./gradlew -q $TASK | xcpretty -c
        shell: bash

  xcode-13:
      name: "${{ matrix.env.name }}"
      runs-on: macos-12
      strategy:
        fail-fast: false
        matrix:
          env:
            - name: "Test iOS 15"
              runtime: "iOS-15-5"
              device: "iPhone 13 Pro"
              task: "testLTRCurrentOS"
            - name: "Test RTL iOS 15"
              runtime: "iOS-15-5"
              device: "iPhone 13 Pro"
              task: "testRTLCurrentOS"
      steps:
        - name: "Select Xcode 13.4.1"
          run: |
            sudo xcode-select -s /Applications/Xcode_13.4.1.app
            xcrun simctl list runtimes
        - name: Git checkout
          uses: actions/checkout@v2
        - name: Run tests
          if: always()
          run: |
            xcrun simctl list devices
            TASK="${{ matrix.env.task }}"
            RUNTIME="${{ matrix.env.runtime }}"
            DEVICE="${{ matrix.env.device }}"
            DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \\-]+/ /g" -e "s/[^[:alnum:]]/-/g")
            RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \\-]+/ /g" -e "s/[^[:alnum:]]/-/g")
            DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
            xcrun simctl boot $DESTINATION_ID
            ./gradlew -q $TASK | xcpretty -c
          shell: bash