name: "edX Test Suit Previos OS"

on:
  - push

jobs:
  xcode-ios:
    name: "${{ matrix.env.name }}"
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: "Test iOS 13.4.1"
            runtime: "iOS-13-4"
            device: "iPhone 8"
            task: "testLTRPreviousOS"
          - name: "Test RTL iOS 13.4.1"
            runtime: "iOS-13-4"
            device: "iPhone 8"
            task: "testRTLPreviousOS"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: "Select Xcode 11.4.1"
      run: |
        ls -n /Applications/ | grep Xcode*
        sudo xcode-select -s /Applications/Xcode_11.4.1.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: Run tests
      if: always()
      run: |
        TASK="${{ matrix.env.task }}"
        RUNTIME="${{ matrix.env.runtime }}"
        DEVICE="${{ matrix.env.device }}"
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        ./gradlew -q $TASK | xcpretty -c
        if [[ $? -eq 0 ]]; then
        echo "Tests passed!" >&2
        else
        echo "Tests failed!" >&2
        fi
      shell: bash