name: "edX Test Suit"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  xcode-ios:
    name: "${{ matrix.env.name }}"
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: "Test iOS 16"
            runtime: "iOS-16-4"
            device: "iPhone 14 Pro"
            task: "testLTRCurrentOS"
          - name: "Test RTL iOS 16"
            runtime: "iOS-16-4"
            device: "iPhone 14 Pro"
            task: "testRTLCurrentOS"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: "Select Xcode 14.3.1"
    run: |
        xcrun simctl list
        sudo xcode-select -s /Applications/Xcode_14.3.1.app
    - name: Run tests
      if: always()
      run: |
        xcrun simctl list
        TASK="${{ matrix.env.task }}"
        RUNTIME="${{ matrix.env.runtime }}"
        DEVICE="${{ matrix.env.device }}"
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        ./gradlew -q $TASK | xcpretty -c
      shell: bash