name: "Fastlane"

on:
  push

jobs:
  test:
    name: "${{ matrix.env.name }}"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: "Test edX LTR"
            scheme: "edX"
          - name: "Test edX RTL"
            scheme: "edX-RTL"
    steps:
      - uses: actions/checkout@v2
      - run: fastlane test scheme:${{ matrix.env.scheme }}