name: "Snapshot Test Case Gradle"

on: [push]

jobs:
  xcode-ios:
    runs-on: macOS-11
    strategy:
      matrix:
        env:
          - xcode: 12.4
            runtime: "iOS-14-5"
            device: "iPhone 8"
          - xcode: 12.4
            runtime: "iOS-12-4"
            device: "iPhone 8"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Link simulator runtimes
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        sudo ln -s /Applications/Xcode_10.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 12.4.simruntime
        sudo ln -s /Applications/Xcode_11.7.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.7.simruntime
    - name: "Select Xcode 12.5.1"
      run: |
        ls -n /Applications/ | grep Xcode*
        sudo xcode-select -s /Applications/Xcode_12.5.1.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: Run tests
      if: always()
      run: |
        RUNTIME="${{ matrix.env.runtime }}"
        DEVICE="${{ matrix.env.device }}"
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        ./gradlew -q testLTRCurrentOS IOS_VERSION=14.5 | xcpretty -c
        if [[ $? -eq 0 ]]; then
        echo "Tests passed." >&2
        else
        echo "Tests didn't pass." >&2
        fi
      shell: bash