name: "test"

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        ios: [14.4, 12.4]
        task: [testLTRCurrentOS, testRTLCurrentOS, testLTRPreviousOS, testRTLPreviousOS]
    steps:
      - name: Run Testcase
        run: ./gradlew verifyTestResults
