name: "TestCurrentOS"

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        id: xcodebuild
        run: |
          sudo xcode-select -s /Applications/Xcode_12.4.app
          instruments -s devices | grep "iPhone 8 14.4" | awk -F '[\[]' '{print $2}' | sed 's/.$//' | xargs open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID
          set -eo pipefail
          ./gradlew -q ${{ matrix.task }} | xcpretty -c || exit ${PIPESTATUS[0]}