name: "TestCurrentOS"

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        ios: [14.4]
        direction: ["", "-RTL"]
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Snapshot Test Cases
        id: xcodebuild
        run: |
          sudo xcode-select -s /Applications/Xcode_12.4.app
          set -eo pipefail
          xcodebuild -workspace edX.xcworkspace -scheme edX${{ matrix.direction }} -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8,OS=${{ matrix.ios }}" test | xcpretty -c || exit ${PIPESTATUS[0]}